version: "3.7"

services:
  app:
    build:
      context: ../
      dockerfile: ../build/service/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - redis
  redis:
    image: redis:6

networks:
  default:
    name: app_network