version: "3.7"

services:
  app:
    build:
      context: ../anti-bruteforce-master
      dockerfile: ../build/service/Dockerfile
    ports:
      - ${GRPC_PORT}:50051
    depends_on:
      - redis
  redis:
    image: redis:6

networks:
  default:
    name: app_network